### PR TITLE
Issue 189

### PR DESCRIPTION
**Pull request by cervantesyu**
Fix raise() implementation for multithreaded program.

### CODE REVIEW

**Comment by cervantesyu** [comment]
From the man page, tkill is obsolete and may result in the wrong thread killed if the tid is recycled. But this is not a problem for raise() implementation because the thread calling raise() will be alive. It's tid will not be used by another thread.

tgkill() has no wrapper in bionic, so if we'd to use it we will be calling it like:
syscall(__NR_tgkill, getpid(), gettid(), signum);

**Comment by kanru** [comment]
I think tkill is fine here, given that there is no tgkill wrapper in bionic it's actually more work to use tgkill.

**Comment by andreasgal** [comment]
With our new repo-style approach we will need a patch for this that we apply over the vendor repo. @michaelwu @cgjones how do you guys want to do this?

**Comment by cervantesyu** [comment]
Per the discussion with Michael Wu today, we may provide the fix upstream or wrap the call.
But I can't find a clean and good way to wrap it inside or outside gecko. Since this bug is still in ICS and the current version is even worse than in Gingerbread, I sent a patch upstream, but I am not sure how long the review process will take.

**Comment by joneschrisg** [comment]
We have three or so small patches we need to apply to vanilla android.
We'll add this to the list.
On Mar 30, 2012 7:28 AM, "CervantesYu" <
reply@reply.github.com>
wrote:

**Comment by michaelwu** [comment]
See https://hg.mozilla.org/mozilla-central/rev/fd2c598e7fde for one example of how calls can be wrapped. The important part is adding a -Wl,--wrap=callname to redirect calls to __wrap_callname, which you then implement in mozglue.

Don't worry about upstreaming. Just wrap the call.

**Comment by cervantesyu** [comment]
If we decide to wrap the call, then what do we do after the original issue gets fixed? Do we file another bug to change it back or just leave the wrapping call in the code base?

**Comment by michaelwu** [comment]
I don't mind leaving the wrapping there. Firefox for Android will need it for some time, at least. We can also detect android versions to turn off wrapping at runtime.

**Pull request closed without merging**
